var car = 'subaru';
console.log(car.toLowerCase() == 'subaru');
console.log(car == 'subaru');
console.log(10 >= 10);
console.log(car != 'ford');
console.log(5 < 3);
console.log(car != 'subaru');
console.log(7 <= 6);
console.log(car == 'toyota');
console.log(car.toLowerCase() == 'SUBARU');
var favoriteCities = ['Paris', 'Tokyo', 'New York', 'London'];
var cityToCheck = 'Tokyo';
console.log(favoriteCities.includes(cityToCheck));
var spokenLanguages = ['English', 'Spanish', 'French', 'Mandarin'];
var languageToCheck = 'German';
console.log(spokenLanguages.includes(languageToCheck));
